### PR TITLE
Docear No Longer Works on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by lackita**
When I upgraded to Ubuntu 18.04, Docear stopped working. I don't
entirely understand the reason, but it was using Object instead of a
more specific type, and this was causing a runtime error.

### CODE REVIEW

**Comment by s-hemer** [comment]
Still complains about  
* Jabref_Beta_2_7_Docear/build.xml:197 source="1.5" target="1.5"
* Jabref_Beta_2_7_Docear/src/java/net/sf/jabref/imports/OpenDatabaseAction.java:375 non-UTF8 char in comment
* Jabref_Beta_2_7_Docear/src/java/net/sf/jabref/groups/GroupTreeNode.java:224: error: incompatible types: Enumeration<TreeNode> cannot be converted to Enumeration<GroupTreeNode>

-> suggest to use (a fork of) https://github.com/JabRef/jabref as a submodule anyway
